main: me.CaptainVelcro.ActualPlugin.Main
name: TheftBEGONE
version: 1.0
author: CaptainVelcro
api-version: 1.13
commands:
  Lock:
  Unlock:
  Databaseadd:
   aliases: dbadd
  upData:
  databaseview:
   aliases: dtbv